/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/AppButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/Card`; params?: Router.UnknownInputParams; } | { pathname: `/components/Icon`; params?: Router.UnknownInputParams; } | { pathname: `/components/ListItem`; params?: Router.UnknownInputParams; } | { pathname: `/components/ListItemDeleteAction`; params?: Router.UnknownInputParams; } | { pathname: `/components/ListItemSeparator`; params?: Router.UnknownInputParams; } | { pathname: `/components/Screen`; params?: Router.UnknownInputParams; } | { pathname: `/components/AppText/AppText`; params?: Router.UnknownInputParams; } | { pathname: `/components/AppText`; params?: Router.UnknownInputParams; } | { pathname: `/components/AppText/styles`; params?: Router.UnknownInputParams; } | { pathname: `/config/colors`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AccountScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ListingDetailsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MessagesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ViewImageScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ListingScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AppButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Card`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Icon`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ListItem`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ListItemDeleteAction`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ListItemSeparator`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Screen`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AppText/AppText`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AppText`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AppText/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/config/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/AccountScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ListingDetailsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/MessagesScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ViewImageScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/WelcomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/ListingScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/AppButton${`?${string}` | `#${string}` | ''}` | `/components/Card${`?${string}` | `#${string}` | ''}` | `/components/Icon${`?${string}` | `#${string}` | ''}` | `/components/ListItem${`?${string}` | `#${string}` | ''}` | `/components/ListItemDeleteAction${`?${string}` | `#${string}` | ''}` | `/components/ListItemSeparator${`?${string}` | `#${string}` | ''}` | `/components/Screen${`?${string}` | `#${string}` | ''}` | `/components/AppText/AppText${`?${string}` | `#${string}` | ''}` | `/components/AppText${`?${string}` | `#${string}` | ''}` | `/components/AppText/styles${`?${string}` | `#${string}` | ''}` | `/config/colors${`?${string}` | `#${string}` | ''}` | `/screens/AccountScreen${`?${string}` | `#${string}` | ''}` | `/screens/ListingDetailsScreen${`?${string}` | `#${string}` | ''}` | `/screens/MessagesScreen${`?${string}` | `#${string}` | ''}` | `/screens/ViewImageScreen${`?${string}` | `#${string}` | ''}` | `/screens/WelcomeScreen${`?${string}` | `#${string}` | ''}` | `/screens/ListingScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/AppButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/Card`; params?: Router.UnknownInputParams; } | { pathname: `/components/Icon`; params?: Router.UnknownInputParams; } | { pathname: `/components/ListItem`; params?: Router.UnknownInputParams; } | { pathname: `/components/ListItemDeleteAction`; params?: Router.UnknownInputParams; } | { pathname: `/components/ListItemSeparator`; params?: Router.UnknownInputParams; } | { pathname: `/components/Screen`; params?: Router.UnknownInputParams; } | { pathname: `/components/AppText/AppText`; params?: Router.UnknownInputParams; } | { pathname: `/components/AppText`; params?: Router.UnknownInputParams; } | { pathname: `/components/AppText/styles`; params?: Router.UnknownInputParams; } | { pathname: `/config/colors`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AccountScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ListingDetailsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MessagesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ViewImageScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/ListingScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
